from __future__ import annotations

import asyncio
from typing import Any

import httpx
from httpx import Client

from ...config import (
    ENDPOINT_COMMUNES,
    ENDPOINT_ENGAGEMENTS,
    ENDPOINT_ENTRAINEURS,
    ENDPOINT_FORMATIONS,
    ENDPOINT_OFFICIELS,
    ENDPOINT_PRATIQUES,
    ENDPOINT_RENCONTRES,
    ENDPOINT_SALLES,
    ENDPOINT_TERRAINS,
    ENDPOINT_TOURNOIS,
)
from ...models.get_commune_response import GetCommuneResponse
from ...models.get_engagement_response import GetEngagementResponse
from ...models.get_entraineur_response import GetEntraineurResponse
from ...models.get_formation_response import GetFormationResponse
from ...models.get_officiel_response import GetOfficielResponse
from ...models.get_pratique_response import GetPratiqueResponse
from ...models.get_rencontre_response import GetRencontreResponse
from ...models.get_salle_response import GetSalleResponse
from ...models.get_terrain_response import GetTerrainResponse
from ...models.get_tournoi_response import GetTournoiResponse
from .._helpers import present_items, run_async

# Endpoint → model class mapping for typed list methods
_LIST_ENDPOINTS: dict[str, type] = {
    "rencontres": GetRencontreResponse,
    "salles": GetSalleResponse,
    "terrains": GetTerrainResponse,
    "tournois": GetTournoiResponse,
    "engagements": GetEngagementResponse,
    "formations": GetFormationResponse,
    "entraineurs": GetEntraineurResponse,
    "communes": GetCommuneResponse,
    "officiels": GetOfficielResponse,
    "pratiques": GetPratiqueResponse,
}

_ENDPOINT_MODULES: dict[str, str] = {
    "rencontres": ENDPOINT_RENCONTRES,
    "salles": ENDPOINT_SALLES,
    "terrains": ENDPOINT_TERRAINS,
    "tournois": ENDPOINT_TOURNOIS,
    "engagements": ENDPOINT_ENGAGEMENTS,
    "formations": ENDPOINT_FORMATIONS,
    "entraineurs": ENDPOINT_ENTRAINEURS,
    "communes": ENDPOINT_COMMUNES,
    "officiels": ENDPOINT_OFFICIELS,
    "pratiques": ENDPOINT_PRATIQUES,
}


class ListMixin:
    """Typed paginated list methods (list_rencontres, list_salles, …)."""

    async_cached_session: httpx.AsyncClient | None
    _list_directus_items_async: Any

    # Method stubs for dynamically generated list methods (setattr at module level)
    # These are generated by _make_list_method() below
    list_rencontres: Any
    list_rencontres_async: Any
    list_salles: Any
    list_salles_async: Any
    list_terrains: Any
    list_terrains_async: Any
    list_tournois: Any
    list_tournois_async: Any
    list_engagements: Any
    list_engagements_async: Any
    list_formations: Any
    list_formations_async: Any
    list_entraineurs: Any
    list_entraineurs_async: Any
    list_communes: Any
    list_communes_async: Any
    list_officiels: Any
    list_officiels_async: Any
    list_pratiques: Any
    list_pratiques_async: Any

    def _typed_list(
        self,
        endpoint: str,
        model_cls: type,
        limit: int = 10,
        filter_criteria: str | None = None,
        sort: list[str] | None = None,
        offset: int | None = None,
        search: str | None = None,
        cached_session: Client | None = None,
    ) -> list:
        return run_async(
            self._typed_list_async(
                endpoint,
                model_cls,
                limit=limit,
                filter_criteria=filter_criteria,
                sort=sort,
                offset=offset,
                search=search,
                cached_session=self.async_cached_session,
            )
        )

    async def _typed_list_async(
        self,
        endpoint: str,
        model_cls: type,
        limit: int = 10,
        filter_criteria: str | None = None,
        sort: list[str] | None = None,
        offset: int | None = None,
        search: str | None = None,
        cached_session: httpx.AsyncClient | None = None,
    ) -> list:
        raw = await self._list_directus_items_async(
            endpoint,
            limit=limit,
            filter_criteria=filter_criteria,
            sort=sort,
            offset=offset,
            search=search,
            cached_session=self.async_cached_session,
        )
        return present_items([model_cls.from_dict(r) for r in raw if r])  # type: ignore[attr-defined]


def _make_list_method(endpoint: str, model_cls: Any, name: str) -> tuple[Any, Any]:
    """Factory: creates sync list_X + async list_X_async pair on ListMixin."""

    def list_method(
        self: Any,
        limit: int = 10,
        filter_criteria: str | None = None,
        sort: list[str] | None = None,
        offset: int | None = None,
        search: str | None = None,
        cached_session: Client | None = None,
    ) -> list:
        return self._typed_list(  # type: ignore[no-any-return]
            endpoint,
            model_cls,
            limit=limit,
            filter_criteria=filter_criteria,
            sort=sort,
            offset=offset,
            search=search,
            cached_session=cached_session,
        )

    async def list_method_async(
        self: Any,
        limit: int = 10,
        filter_criteria: str | None = None,
        sort: list[str] | None = None,
        offset: int | None = None,
        search: str | None = None,
        cached_session: httpx.AsyncClient | None = None,
    ) -> list:
        return await self._typed_list_async(  # type: ignore[no-any-return]
            endpoint,
            model_cls,
            limit=limit,
            filter_criteria=filter_criteria,
            sort=sort,
            offset=offset,
            search=search,
            cached_session=cached_session,
        )

    list_method.__name__ = name
    list_method.__qualname__ = f"ListMixin.{name}"
    list_method_async.__name__ = f"{name}_async"
    list_method_async.__qualname__ = f"ListMixin.{name}_async"
    return list_method, list_method_async


for _name, _cls in _LIST_ENDPOINTS.items():
    _endpoint = _ENDPOINT_MODULES[_name]
    _sync, _async = _make_list_method(_endpoint, _cls, f"list_{_name}")
    setattr(ListMixin, f"list_{_name}", _sync)
    setattr(ListMixin, f"list_{_name}_async", _async)


class ListAllMixin:
    """Auto-paginated typed list methods (list_all_rencontres, list_all_salles, …)."""

    async_cached_session: httpx.AsyncClient | None
    _list_directus_items_async: Any

    # Method stubs for dynamically generated list_all methods (setattr at module level)
    list_all_rencontres: Any
    list_all_rencontres_async: Any
    list_all_salles: Any
    list_all_salles_async: Any
    list_all_terrains: Any
    list_all_terrains_async: Any
    list_all_tournois: Any
    list_all_tournois_async: Any
    list_all_engagements: Any
    list_all_engagements_async: Any
    list_all_formations: Any
    list_all_formations_async: Any
    list_all_entraineurs: Any
    list_all_entraineurs_async: Any
    list_all_communes: Any
    list_all_communes_async: Any
    list_all_officiels: Any
    list_all_officiels_async: Any
    list_all_pratiques: Any
    list_all_pratiques_async: Any

    async def _list_all_directus_items_async(
        self,
        endpoint: str,
        model_cls: type,
        filter_criteria: str | None = None,
        sort: list[str] | None = None,
        search: str | None = None,
        page_size: int = 100,
        max_items: int = 10000,
        cached_session: httpx.AsyncClient | None = None,
    ) -> list:
        first_batch = await self._list_directus_items_async(
            endpoint,
            limit=page_size,
            filter_criteria=filter_criteria,
            sort=sort,
            offset=0,
            search=search,
            cached_session=self.async_cached_session,
        )
        if not first_batch:
            return []
        results = [model_cls.from_dict(r) for r in first_batch if r]  # type: ignore[attr-defined]
        if len(first_batch) < page_size or len(results) >= max_items:
            return results[:max_items]
        total_pages = min((max_items + page_size - 1) // page_size, 20)
        remaining_tasks = [
            self._list_directus_items_async(
                endpoint,
                limit=page_size,
                filter_criteria=filter_criteria,
                sort=sort,
                offset=i * page_size,
                search=search,
                cached_session=self.async_cached_session,
            )
            for i in range(1, total_pages)
        ]
        remaining_batches = await asyncio.gather(*remaining_tasks)
        for batch in remaining_batches:
            if not batch:
                break
            results.extend([model_cls.from_dict(r) for r in batch if r])  # type: ignore[attr-defined]
            if len(batch) < page_size:
                break
        return results[:max_items]

    def _list_all(
        self,
        endpoint: str,
        model_cls: Any,
        filter_criteria: str | None = None,
        sort: list[str] | None = None,
        search: str | None = None,
        page_size: int = 100,
        max_items: int = 10000,
        cached_session: Client | None = None,
    ) -> list:
        return run_async(
            self._list_all_directus_items_async(
                endpoint,
                model_cls,
                filter_criteria=filter_criteria,
                sort=sort,
                search=search,
                page_size=page_size,
                max_items=max_items,
                cached_session=self.async_cached_session,
            )
        )


def _make_list_all_method(endpoint: str, model_cls: Any, name: str) -> tuple[Any, Any]:
    """Factory: creates sync list_all_X + async list_all_X_async pair on ListAllMixin."""

    def list_all_method(
        self: Any,
        filter_criteria: str | None = None,
        sort: list[str] | None = None,
        search: str | None = None,
        page_size: int = 100,
        max_items: int = 10000,
        cached_session: Client | None = None,
    ) -> list:
        return self._list_all(  # type: ignore[no-any-return]
            endpoint,
            model_cls,
            filter_criteria=filter_criteria,
            sort=sort,
            search=search,
            page_size=page_size,
            max_items=max_items,
            cached_session=cached_session,
        )

    async def list_all_method_async(
        self: Any,
        filter_criteria: str | None = None,
        sort: list[str] | None = None,
        search: str | None = None,
        page_size: int = 100,
        max_items: int = 10000,
        cached_session: httpx.AsyncClient | None = None,
    ) -> list:
        return await self._list_all_directus_items_async(  # type: ignore[no-any-return]
            endpoint,
            model_cls,
            filter_criteria=filter_criteria,
            sort=sort,
            search=search,
            page_size=page_size,
            max_items=max_items,
            cached_session=cached_session,
        )

    list_all_method.__name__ = name
    list_all_method.__qualname__ = f"ListAllMixin.{name}"
    list_all_method_async.__name__ = f"{name}_async"
    list_all_method_async.__qualname__ = f"ListAllMixin.{name}_async"
    return list_all_method, list_all_method_async


for _name, _cls in _LIST_ENDPOINTS.items():
    _endpoint = _ENDPOINT_MODULES[_name]
    _sync, _async = _make_list_all_method(_endpoint, _cls, f"list_all_{_name}")
    setattr(ListAllMixin, f"list_all_{_name}", _sync)
    setattr(ListAllMixin, f"list_all_{_name}_async", _async)
